'use strict';
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}),headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const artifact=path.resolve(__dirname,'../中转站测试工具-多模态版.html');
 await page.goto(pathToFileURL(artifact).href);
 await page.screenshot({path:path.join(__dirname,'qa-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'体验预览',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===4&&document.getElementById('runBtn').disabled===false);
 assert.equal(await page.locator('.status.demo').count(),4);
 await page.waitForFunction(()=>[...document.querySelectorAll('.media-item img')].every(i=>i.complete&&i.naturalWidth>0));
 await page.waitForFunction(()=>[...document.querySelectorAll('.media-item audio,.media-item video')].every(i=>i.readyState>=1));
 await page.screenshot({path:path.join(__dirname,'qa-media.png'),fullPage:true});
 const demoDownload=page.waitForEvent('download');await page.locator('#exportBtn').click();const dl=await demoDownload;const reportFile=path.join(__dirname,'qa-demo-report.html');await dl.saveAs(reportFile);
 const report=await browser.newPage();await report.goto(pathToFileURL(reportFile).href);assert.equal(await report.locator('video').count(),1);assert.equal(await report.locator('audio').count(),1);assert.equal(await report.locator('img').count(),1);await report.waitForFunction(()=>document.querySelector('img').naturalWidth>0);await report.close();
 await page.locator('#clearBtn').click();
 const calls=[];let polls=0;
 const wav=Buffer.alloc(44+4800);wav.write('RIFF');wav.writeUInt32LE(4836,4);wav.write('WAVE',8);wav.write('fmt ',12);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(24000,24);wav.writeUInt32LE(48000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(4800,40);
 const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8qkAAAAASUVORK5CYII=';
 await page.route('https://relay.test/**',async route=>{
   const req=route.request();const url=new URL(req.url());calls.push({path:url.pathname,method:req.method(),body:req.postData(),auth:req.headers().authorization});
   const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*','content-type':'application/json'};
   if(req.method()==='OPTIONS')return route.fulfill({status:204,headers});
   if(url.pathname==='/v1/slow'){await new Promise(r=>setTimeout(r,1500));return route.fulfill({headers,body:JSON.stringify({choices:[{message:{content:'slow response'}}]})}).catch(()=>{});}
   if(url.pathname==='/v1/models')return route.fulfill({headers,body:JSON.stringify({data:[{id:'text-test'},{id:'image-test'}]})});
   if(url.pathname==='/v1/audio/speech')return route.fulfill({headers:{...headers,'content-type':'audio/wav'},body:wav});
   if(url.pathname==='/v1/audio/transcriptions')return route.fulfill({headers,body:JSON.stringify({text:'你好，语音转写测试完成。'})});
   if(url.pathname==='/v1/chat/completions')return route.fulfill({headers,body:JSON.stringify({model:'text-test',choices:[{message:{content:'测试通过：17 × 23 = 391。'}}]})});
   if(url.pathname==='/v1/images/generations')return route.fulfill({headers,body:JSON.stringify({data:[{b64_json:png}],debug_key:'mock-secret-123'})});
   if(url.pathname==='/v1/videos'&&req.method()==='POST')return route.fulfill({status:202,headers,body:JSON.stringify({id:'video-task-1',status:'queued'})});
   if(url.pathname==='/v1/videos/video-task-1')return route.fulfill({headers,body:JSON.stringify(++polls<2?{id:'video-task-1',status:'in_progress'}:{id:'video-task-1',status:'completed',video_url:'https://cdn.test/demo.mp4'})});
   return route.fulfill({status:400,headers,body:JSON.stringify({error:{message:'unsupported test path'}})});
 });
 await page.locator('#base').fill('https://relay.test/v1');await page.locator('#key').fill('mock-secret-123');await page.locator('#model').fill('text-test');
 await page.locator('#loadModels').click();await page.waitForFunction(()=>document.querySelectorAll('#modelList .model-option').length===2);
 await page.locator('#previewBtn').click();assert.ok((await page.locator('#requestPreview').innerText()).includes('/v1/chat/completions'));assert.ok(!(await page.locator('#requestPreview').innerText()).includes('mock-secret-123'));await page.locator('#closePreview').click();
 await page.locator('#runBtn').click();await page.waitForFunction(()=>document.querySelector('.result-text')?.textContent.includes('391')&&!document.getElementById('runBtn').disabled);
 await page.locator('[data-kind=image]').click();await page.locator('#model').fill('image-test');await page.locator('#runBtn').click();await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===2&&!document.getElementById('runBtn').disabled);
 assert.equal(await page.locator('.result-card').first().locator('img').count(),1);
 await page.locator('[data-kind=video]').click();await page.locator('#model').fill('video-test');await page.locator('.advanced summary').click();await page.locator('#pollInterval').fill('1');await page.locator('#runBtn').click();
 await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===3&&!document.getElementById('runBtn').disabled);
 assert.equal(await page.locator('.result-card').first().locator('video').count(),1);assert.equal(await page.locator('#taskId').inputValue(),'video-task-1');
 const postCount=calls.filter(c=>c.path==='/v1/videos'&&c.method==='POST').length;
 await page.locator('#resumeBtn').click();await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===4&&!document.getElementById('runBtn').disabled);
 assert.equal(calls.filter(c=>c.path==='/v1/videos'&&c.method==='POST').length,postCount);
 await page.locator('[data-kind=audio]').click();await page.locator('#model').fill('tts-test');await page.locator('#runBtn').click();await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===5&&!document.getElementById('runBtn').disabled);assert.equal(await page.locator('.result-card').first().locator('audio').count(),1);
 await page.locator('#preset').selectOption('openai-transcription');await page.locator('#model').fill('whisper-test');await page.locator('#files').setInputFiles({name:'sample.wav',mimeType:'audio/wav',buffer:wav});await page.locator('#runBtn').click();await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===6&&!document.getElementById('runBtn').disabled);assert.ok((await page.locator('.result-card').first().innerText()).includes('语音转写测试完成'));
 await page.locator('#base').fill('https://other.test');await page.locator('#key').fill('other-key');await page.getByText('载入查询配置',{exact:true}).first().click();assert.equal(await page.locator('#key').inputValue(),'');assert.equal(await page.locator('#base').inputValue(),'https://relay.test/v1');
 await page.locator('#key').fill('mock-secret-123');const d2=page.waitForEvent('download');await page.locator('#exportBtn').click();const d=await d2;const p2=path.join(__dirname,'qa-mock-report.html');await d.saveAs(p2);assert.ok(!fs.readFileSync(p2,'utf8').includes('mock-secret-123'));
 await page.locator('#clearBtn').click();await page.locator('[data-kind=text]').click();await page.locator('#model').fill('text-test');await page.locator('#batch').fill('batch-a, batch-b');await page.locator('#runBtn').click();await page.waitForFunction(()=>document.querySelectorAll('.result-card').length===2&&!document.getElementById('runBtn').disabled);assert.equal(await page.locator('.result-card h3').first().innerText(),'batch-b');
 await page.locator('#batch').fill('');await page.locator('#path').fill('/v1/slow');await page.locator('#runBtn').click();await page.waitForFunction(()=>document.getElementById('runBtn').disabled);await page.locator('#stopBtn').click();await page.waitForFunction(()=>!document.getElementById('runBtn').disabled);assert.equal(await page.locator('.status.stopped').count(),1);
 await page.locator('[data-kind=text]').click();await page.locator('#legacyBtn').click();const frame=page.frameLocator('#legacyFrame');await frame.locator('#inBase').waitFor();assert.equal(await frame.locator('#btnRun').count(),1);await page.locator('#backBtn').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'qa-mobile.png'),fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile layout must not overflow');
 assert.deepEqual(errors,[],'no browser runtime errors');
 fs.writeFileSync(path.join(__dirname,'qa-summary.json'),JSON.stringify({passed:true,browser:'Chrome / Playwright',checks:['standalone file load','four local media demos','embedded media report','model discovery','masked request preview','text response','image response','video polling','speech binary playback','audio multipart transcription','resume without POST','cross-channel key clear','report secret redaction','same-protocol batch','immediate cancellation','legacy iframe','mobile no overflow','no JS errors'],requestCount:calls.length},null,2));
 console.log('PASS: standalone, local media playback, reports, model discovery, request preview, text/image/video, resume, key boundaries, legacy, mobile, console');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
